### ISSUE TITLE
CI workflows disabled

### ISSUE THREAD

**Issue by JostMigenda** [HKDAQ/FLOWER#29]
The CI workflows added in #26 are failing, because they require repository secrets which are not currently set. I have [disabled them](https://docs.github.com/en/actions/using-workflows/disabling-and-enabling-a-workflow) for now.

@guiguem: Currently @brichards64 is the only admin of the HKDAQ org, and thus afaict the only person able to configure secrets for this repository. Can you discuss the configuration with Ben before we re-enable the workflows?

**Comment by guiguem** [comment]
Right! I think if one wants to use this software for production in the near future, this should be transitioned to the hyperk organisation where we can ensure proper maintenance.
Do you see any issues with this move (e.g. software or copyright wise)? If not, then we should discuss with Ben about doing this and then we can update the secrets etc...

**Comment by JostMigenda** [comment]
Since using FLOWER necessarily requires a vertex fitter like [hk-BONSAI](https://github.com/hyperk/hk-BONSAI) or [LEAF](https://github.com/hyperk/LEAF)—which are both already located under the hyperk org!—I don’t see any issues with that move, no. Whereas having it under a different org than other sim/reco packages _is_ clearly causing issues.

GitHub [is very good about forwarding any URLs](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) referencing a transferred repo, so this shouldn’t cause much of a migration burden, either.

_(For historical context: The reason we moved it to the HKDAQ org in May 2020—it was under my personal account before that—was because we inside the DAQ group were discussing how to integrate it into a SN trigger (see #10); we didn’t think much about whether another org may be a better choice.)_

**Comment by JostMigenda** [comment]
We talked about this earlier today at the HK UK PSC meeting and agreed that @brichards64 will move the repo to the hyperk org. Then you and @sk1806 will be able to admin the repo as needed, create new tags for HK software releases, etc.

**Comment by tdealtry** [comment]
Will resurrect the CI after the move to HK gitlab
